services:
  - type: web
    name: music-store-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/locales
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
